-- create or replace function calculate_time (start_time in date, end_time in date)
--               return float is
--               vTime float;
-- begin
-- select 24 * (end_time - start_time) into vTime from dual;
-- return CEIL(vTime);
-- end;
--
-- create or replace function count_payment (price IN Integer, time_calculated IN Integer)
--               return float is
--               total_price float;
-- begin
-- select price * time_calculated into total_price from dual;
-- return total_price;
-- end;
--
-- -- SELECT count_payment(6.33232,10) from dual;
-- -- SELECT calculate_time(to_date('2012-02-28 15:20', 'YYYY-MM-DD hh24:mi'),to_date('2012-02-28 16:21', 'YYYY-MM-DD hh24:mi')) from dual;
--
-- CREATE OR REPLACE PROCEDURE update_price
-- (rental_id IN Integer, total_price IN Integer)
-- IS
-- BEGIN
-- UPDATE Rental
-- SET PRICE = total_price
-- WHERE Rental.ID = rental_id;
-- END update_price;
